### ISSUE TITLE
TypeError: 'NoneType' object is not subscriptable

### ISSUE THREAD

**Issue by ravirajlondhepatil** [angelbroking-github/smartapi-python#15]
Hi,
I am getting below error,
'''
  File "/Users/ravirajlondhe/Desktop/New_Project/venv/lib/python3.7/site-packages/smartapi/smartConnect.py", line 253, in generateSession
    id=user['data']['clientcode']
TypeError: 'NoneType' object is not subscriptable
'''
can someone guide me?

**Comment by gauravrock** [comment]
@admin I am also facing the same issue of Nonetype data! is anyone working on this one
![Screenshot 2021-02-10 at 10 30 34 PM](https://user-images.githubusercontent.com/23530368/107544444-3de9fd00-6bf0-11eb-80e8-6ed04b9a93c4.png)

**Comment by nikhilsingh291** [comment]
@ravirajlondhepatil @gauravrock   This is probably because you are providing wrong login credentials. 
data = obj.generateSession("Your Client ID","Your Password")
if the client id and password are wrong , the data json response will not have the "refreshToken", hence the error.

use try except to handle this error

`from smartapi import SmartConnect
obj=SmartConnect(api_key="your api key")
data = obj.generateSession("Your Client ID","Your Password")
try:
    refreshToken= data['data']['refreshToken']
except Exception as error:
    print("Login error:",error)
if refreshToken:
    feedToken=obj.getfeedToken()
    userProfile= obj.getProfile(refreshToken)`

**Comment by Mohammed-Sunasra** [comment]
From where should we get the "Client ID"?

**Comment by nikhilsingh291** [comment]
> From where should we get the "Client ID"?

Register on Angel Broking and get your Client ID.
Check their smart api documentation for details
